routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', 'users');

Route::prefix('users')->name('users.')->group(function() {
    Route::get('', 'UsersController@index')->name('index');
    Route::get('create', 'UsersController@create')->name('create');
    Route::post('store', 'UsersController@store')->name('store');
    Route::get('{user}', 'UsersController@show')->name('show');
    Route::post('{user}/exchange', 'UsersController@exchange')->name('exchange');
});

app/Models/Currency.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Currency extends Model
{
    //
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function currency() {
        return $this->belongsTo('App\Models\Currency', 'currency_id');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests\SaveUser;

use App\Models\Currency;
use App\Models\User;

use CurrencyExchanger;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::paginate(10);
        return view('frontend.users.index')->with(compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $currencies = Currency::all();
        return view('frontend.users.save')->with(compact('currencies'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SaveUser $request)
    {
        $user = new User;
        $user->name         = $request->get('name');
        $user->email        = $request->get('email');
        $user->rate         = $request->get('rate');
        $user->currency_id  = $request->get('currency_id');
        $user->password     = '';
        $user->save();

        return redirect()->route('users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        $currencies = Currency::all();
        return view('frontend.users.show')->with(compact('user', 'currencies'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function exchange(Request $request, User $user) {
        $currency = Currency::findOrFail($request->currency_id);
        $new_amount = CurrencyExchanger::from($user->currency->code)->to($currency->code)->amount($user->rate)->convert();

        return response()->json(array('data' => array('new_amount' => $new_amount, 'new_currency' => $currency->code)));
    }
}

resources/views/frontend/users/index.blade.php
@extends('layouts.frontend')

@section('content')
    <section class="container mt-4">
        <div class="row mb-4">
            <div class="offset-md-9 col-md-3 col-12">
                <a href="{{ route('users.create') }}" class="btn btn-block btn-primary">Register Freelancer</a>
            </div>
        </div>
        @forelse ($users as $user)
            <div class="card col-12 mb-4">
                <div class="card-body">
                    <h5 class="card-title">{{ $user->name }}</h5>
                <p class="card-text">Click View User Details to view more information regarding the freelancer.</p><p>
                     <strong>{{ $user->rate . " " . $user->currency->code . " per hour" }}. </strong></p>
                    <a href="{{ route('users.show', compact('user')) }}" class="btn btn-primary">View user details</a>
                </div>
            </div>
        @empty
            <div class="card col-12">
                <div class="card-body">
                    <p class="card-text">No freelancers are currently registered. Please register a new one</p>
                </div>
            </div>
        @endforelse
        {{ $users->links() }}
    </section>
@stop

resources/views/frontend/users/save.blade.php
@extends('layouts.frontend')

@push('styles')
    <style>
        .required:after {
            content: " *";
            color: red;
        }
    </style>
@endpush

@section('content')
    <section class="container mt-4">
        <div class="card col-12 p-4">
            <form method="POST" action="{{ route('users.store') }}">
                {{ csrf_field() }}
                <div class="row">
                    <div class="col-12 col-md-6">
                        <label for="name" class="required">Name</label>
                        <input type="text" name="name" id="name" class="form-control">
                        @if($errors->has('name'))
                            <p class="text-danger">{{ $errors->first('name') }}</p>
                        @endif
                    </div>
                    <div class="col-12 col-md-6">
                        <label for="email" class="required">Email</label>
                        <input type="text" name="email" id="email" class="form-control">
                        @if($errors->has('email'))
                            <p class="text-danger">{{ $errors->first('email') }}</p>
                        @endif
                    </div>
                    <div class="col-12 col-md-6">
                        <label for="rate" class="required">Hourly Rate</label>
                        <input type="text" name="rate" id="rate" class="form-control">
                        @if($errors->has('rate'))
                            <p class="text-danger">{{ $errors->first('rate') }}</p>
                        @endif
                    </div>
                    <div class="col-12 col-md-6">
                        <label for="currency_id" class="required">Currency</label>
                        <select name="currency_id" id="currency_id" class="form-control">
                            <option value="">Please choose the currency in which you would prefer to be paid</option>
                            @foreach($currencies as $currency)
                                <option value="{{ $currency->id }}">{{ $currency->name }}</option>
                            @endforeach
                        </select>
                        @if($errors->has('currency_id'))
                            <p class="text-danger">{{ $errors->first('currency_id') }}</p>
                        @endif
                    </div>
                    <div class="col-md-3 offset-md-6 col-12 float-right mt-4">
                        <a href="{{ route('users.index') }}" class="btn btn-block btn-danger">Cancel</a>
                    </div>
                    <div class="col-md-3 col-12 float-right mt-4">
                        <button type="submit" class="btn btn-block btn-primary">Register</button>
                    </div>
                </div>
            </form>
        </div>
    </section>
@stop

resources/views/frontend/users/show.blade.php
@extends('layouts.frontend')

@push('styles')
    <style>
        .required:after {
            content: " *";
            color: red;
        }
    </style>
@endpush

@section('content')
    <section class="container mt-4">
        <div class="card col-12 p-4">
            <h5 class="card-title">{{ $user->name }}</h5>
            <p class="card-text text-muted">{{ $user->email }}</p>
            <p class="card-text">{{ $user->rate . " " . $user->currency->code . " per hour" }}</p>
        </div>
        <div class="card col-12 p-4 mt-4">
            <form method="POST" action="{{ route('users.exchange', compact('user')) }}">
                {{ csrf_field() }}
                <div class="row">
                    <div class="col-12">
                        <label for="currency_id" class="required">Exchange To</label>
                        <select name="currency_id" id="currency_id" class="form-control">
                            <option value="">Please choose the currency in which you would prefer to be paid</option>
                            @foreach($currencies as $currency)
                                <option value="{{ $currency->id }}">{{ $currency->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="md-offset-9 col-md-3 col-12 float-right mt-4">
                        <button type="submit" class="btn btn-block btn-primary">Exchange</button>
                    </div>
                </div>
            </form>
        </div>
    </section>
@stop

resources/views/layouts/core.blade.php
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        @stack('styles')
    </head>
    <body class="bg-light">

        @yield('main')

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
        @stack('scripts')
    </body>
</html>

resources/views/layouts/frontend.blade.php
@extends('layouts.core')

@section('main')
    @include('partials.frontend.header')

    @yield('content')

    @include('partials.frontend.footer')
@stop

resources/views/partials/frontend/header.blade.php
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
    <a href="{{ url('') }}" class="navbar-brand text-white">Home</a>
</nav>